### ISSUE TITLE
fatal: remote origin already exists.

### ISSUE THREAD

**Issue by mehulkar** [edgecase/middleman-gh-pages#24] opened 2014-12-31 01:56 UTC
```
❯ rake publish
******
cd /Users/mehulkar/dev/personal/mehulkar.github.io
cd -
cd /Users/mehulkar/dev/personal/mehulkar.github.io/build
git init
Reinitialized existing Git repository in /Users/mehulkar/dev/personal/mehulkar.github.io/build/.git/
git remote add origin git@github.com:mehulkar/mehulkar.github.io.git
fatal: remote origin already exists.
rake aborted!
Command failed with status (128): [git remote add origin git@github.com:mehul...]
/Users/mehulkar/.rvm/gems/ruby-2.1.1/gems/middleman-gh-pages-0.0.3/lib/middleman-gh-pages/tasks/gh-pages.rake:22:in `block (2 levels) in <top (required)>'
/Users/mehulkar/.rvm/gems/ruby-2.1.1/gems/middleman-gh-pages-0.0.3/lib/middleman-gh-pages/tasks/gh-pages.rake:20:in `block in <top (required)>'
/Users/mehulkar/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/mehulkar/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => publish => prepare_git_remote_in_build_dir => /Users/mehulkar/dev/personal/mehulkar.github.io/build/.git/refs/remotes/origin/gh-pages
(See full trace by running task with --trace)
```

**Comment by marcamillion** [comment] 2015-03-16 14:35
+1 on this issue. Are there any fixes for this yet?

**Comment by localredhead** [comment] 2015-03-23 04:16
+1 anyone have any insight?

**Comment by ToddAT** [comment] 2015-05-27 17:18
+1 Just tried using this and am running into the same issue. Any update?

**Comment by maggieoconnor** [comment] 2015-10-08 15:10
This fix should do it for me. Can we get this merged and deployed to rubygems?

**Closed** 2016-02-16 20:36 UTC

**Comment by kakoni** [comment] 2016-02-22 21:57
Question, was this fix actually pushed to master? (dont see it?)

**Comment by rmm5t** [comment] 2016-02-23 01:00
> Question, was this fix actually pushed to master? (dont see it?)

It was, but then it was immediately reverted,  because it was problematic with brand new `build` directory initialization. 

Instead, if you still have this error with the latest version of middleman-gh-pages,  just blow away your `build` directory and run `rake publish` again. Afterwards, everything should be back in sync. 

If there is still trouble after that,  please report back,  and we'll investigate a more appropriate fix.

**Comment by milesalex** [comment] 2016-03-16 02:11
The issue is still happening for me after I delete the build directory

**Comment by rmm5t** [comment] 2016-03-16 18:33
@milesalex Thanks for chiming in here. To help further debug this, would you mind pasting here both the output of `bundle list | grep middleman-gh` and the output of `bundle exec rake publish --trace` (after the `build` directory is removed with `rm -rf build`)?

**Comment by rmm5t** [comment] 2016-04-13 23:48
For those that are still having issues with this particular issue of "fatal: remote origin already exists" ...

Is it possible that you have a `remove.origin` config in your global git config (`~/.gitconfig`)? It would look something like this:

```
[remote "origin"]
  # ...
  # specific config for origin remotes
  # ...
```

It's best not to have a global config for your origin remote like this. Otherwise, git is tricked into thinking that an origin remote already exists on all new `git init` repositories.
