### ISSUE TITLE
Cannot run "rake publish ALLOW_DIRTY=true" 

### ISSUE THREAD

**Issue by haroldherbert** [edgecase/middleman-gh-pages#22] opened 2014-06-03 09:14 UTC
When I run:
 ```
bundle exec rake publish ALLOW_DIRTY=true 
```
it continually yields: 

```
...
rake aborted!
Command failed with status (1): [bundle exec middleman build --clean...]
/Library/Ruby/Gems/2.0.0/gems/middleman-gh-pages-0.0.3/lib/middleman-gh-pages/tasks/gh-pages.rake:60:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/middleman-gh-pages-0.0.3/lib/middleman-gh-pages/tasks/gh-pages.rake:59:in `block in <top (required)>'
Tasks: TOP => publish => build
(See full trace by running task with --trace)
```

Stuck here. Any help appreciated!

**Comment by kbrock** [comment] 2015-05-25 04:31
I wonder if you would have more luck with:
```bash
ALLOW_DIRTY=true bundle exec rake publish
```

**Comment by wkoszek** [comment] 2015-11-27 21:15
@haroldherbert I just upgraded my system and even without `ALLOW_DIRTY` it's broken. But the good thing is that middleman-deploy does work.

**Comment by rmm5t** [comment] 2016-02-16 21:17
>  I just upgraded my system and even without ALLOW_DIRTY it's broken

Yes, based on your error output, this doesn't look like it's related to your`ALLOW_DIRTY` config. It looks like `middleman build` had a non-zero exit status. Likely caused by something unrelated to the project, but I cannot be sure without more details.

Closing this for now. Just chime back in if you want it re-opened.

**Closed by rmm5t** 2016-02-16 21:17 UTC
